---
- name: install required packages
  apt:
    name: ['git', 'default-jdk', 'maven']
    state: present
    update_cache: true

- name: Clone source code from git
  git:
    repo: https://github.com/ag4544/boxfuse-sample.git
    dest: /var/boxfuse-sample/

- name: Compile from source
  shell: mvn package
  args:
    chdir: /var/boxfuse-sample/
  