---
- name: install required packages
  apt:
    name: ['default-jdk', 'tomcat9']
    state: present
    update_cache: true

- name: Remove ROOT dir from tomcat 
  file:
    path: /var/lib/tomcat9/webapps/ROOT
    state: absent

- name: RSYNC building artefacts
  synchronize:
    src: "{{ groups.builder | first }}":/var/boxfuse-sample/target/hello-1.0.war
    dest: /var/lib/tomcat9/webapps/ROOT.war
  delegate_to: "{{ groups.webserver | first }}"
  notify: 
  - restart tomcat9
